// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.6
// source: murouse/membrane/v1/membrane.proto

package membranev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_ADMIN       Role = 2 // you can add
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_murouse_membrane_v1_membrane_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_murouse_membrane_v1_membrane_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_murouse_membrane_v1_membrane_proto_rawDescGZIP(), []int{0}
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnyOf       []Role  `protobuf:"varint,1,rep,packed,name=any_of,json=anyOf,proto3,enum=murouse.membrane.v1.Role" json:"any_of,omitempty"` // Достаточно иметь ХОТЯ БЫ ОДНУ из этих ролей (OR)
	AllOf       []Role  `protobuf:"varint,2,rep,packed,name=all_of,json=allOf,proto3,enum=murouse.membrane.v1.Role" json:"all_of,omitempty"` // Нужно иметь ВСЕ эти роли одновременно (AND)
	NestedAnyOf []*Rule `protobuf:"bytes,3,rep,name=nested_any_of,json=nestedAnyOf,proto3" json:"nested_any_of,omitempty"`                   // Связываются через ИЛИ (Хотя бы одно вложенное правило должно сработать)
	NestedAllOf []*Rule `protobuf:"bytes,4,rep,name=nested_all_of,json=nestedAllOf,proto3" json:"nested_all_of,omitempty"`                   // Связываются через И (Все вложенные правила должны сработать)
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_murouse_membrane_v1_membrane_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_murouse_membrane_v1_membrane_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_murouse_membrane_v1_membrane_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetAnyOf() []Role {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

func (x *Rule) GetAllOf() []Role {
	if x != nil {
		return x.AllOf
	}
	return nil
}

func (x *Rule) GetNestedAnyOf() []*Rule {
	if x != nil {
		return x.NestedAnyOf
	}
	return nil
}

func (x *Rule) GetNestedAllOf() []*Rule {
	if x != nil {
		return x.NestedAllOf
	}
	return nil
}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowUnauthenticated bool  `protobuf:"varint,1,opt,name=allow_unauthenticated,json=allowUnauthenticated,proto3" json:"allow_unauthenticated,omitempty"`
	Rule                 *Rule `protobuf:"bytes,2,opt,name=rule,proto3,oneof" json:"rule,omitempty"`
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_murouse_membrane_v1_membrane_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_murouse_membrane_v1_membrane_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_murouse_membrane_v1_membrane_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetAllowUnauthenticated() bool {
	if x != nil {
		return x.AllowUnauthenticated
	}
	return false
}

func (x *Policy) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var file_murouse_membrane_v1_membrane_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Policy)(nil),
		Field:         51235,
		Name:          "murouse.membrane.v1.policy",
		Tag:           "bytes,51235,opt,name=policy",
		Filename:      "murouse/membrane/v1/membrane.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional murouse.membrane.v1.Policy policy = 51235;
	E_Policy = &file_murouse_membrane_v1_membrane_proto_extTypes[0]
)

var File_murouse_membrane_v1_membrane_proto protoreflect.FileDescriptor

var file_murouse_membrane_v1_membrane_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61,
	0x6e, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d, 0x65,
	0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x04,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x6e, 0x79, 0x5f, 0x6f, 0x66, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x05, 0x61, 0x6e, 0x79, 0x4f, 0x66, 0x12, 0x30, 0x0a, 0x06, 0x61, 0x6c, 0x6c, 0x5f, 0x6f, 0x66,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65,
	0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x05, 0x61, 0x6c, 0x6c, 0x4f, 0x66, 0x12, 0x3d, 0x0a, 0x0d, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x6e, 0x79, 0x5f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61,
	0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0b, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x41, 0x6e, 0x79, 0x4f, 0x66, 0x12, 0x3d, 0x0a, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0b, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x66, 0x22, 0x7a, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x33, 0x0a, 0x15, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x14, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d, 0x65,
	0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x48, 0x00,
	0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x75,
	0x6c, 0x65, 0x2a, 0x3b, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x3a,
	0x55, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa3, 0x90, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x6d, 0x65, 0x6d, 0x62,
	0x72, 0x61, 0x6e, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x6d,
	0x62, 0x72, 0x61, 0x6e, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x75,
	0x72, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x6d, 0x65, 0x6d, 0x62, 0x72, 0x61, 0x6e, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_murouse_membrane_v1_membrane_proto_rawDescOnce sync.Once
	file_murouse_membrane_v1_membrane_proto_rawDescData = file_murouse_membrane_v1_membrane_proto_rawDesc
)

func file_murouse_membrane_v1_membrane_proto_rawDescGZIP() []byte {
	file_murouse_membrane_v1_membrane_proto_rawDescOnce.Do(func() {
		file_murouse_membrane_v1_membrane_proto_rawDescData = protoimpl.X.CompressGZIP(file_murouse_membrane_v1_membrane_proto_rawDescData)
	})
	return file_murouse_membrane_v1_membrane_proto_rawDescData
}

var file_murouse_membrane_v1_membrane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_murouse_membrane_v1_membrane_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_murouse_membrane_v1_membrane_proto_goTypes = []any{
	(Role)(0),                          // 0: murouse.membrane.v1.Role
	(*Rule)(nil),                       // 1: murouse.membrane.v1.Rule
	(*Policy)(nil),                     // 2: murouse.membrane.v1.Policy
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_murouse_membrane_v1_membrane_proto_depIdxs = []int32{
	0, // 0: murouse.membrane.v1.Rule.any_of:type_name -> murouse.membrane.v1.Role
	0, // 1: murouse.membrane.v1.Rule.all_of:type_name -> murouse.membrane.v1.Role
	1, // 2: murouse.membrane.v1.Rule.nested_any_of:type_name -> murouse.membrane.v1.Rule
	1, // 3: murouse.membrane.v1.Rule.nested_all_of:type_name -> murouse.membrane.v1.Rule
	1, // 4: murouse.membrane.v1.Policy.rule:type_name -> murouse.membrane.v1.Rule
	3, // 5: murouse.membrane.v1.policy:extendee -> google.protobuf.MethodOptions
	2, // 6: murouse.membrane.v1.policy:type_name -> murouse.membrane.v1.Policy
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	6, // [6:7] is the sub-list for extension type_name
	5, // [5:6] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_murouse_membrane_v1_membrane_proto_init() }
func file_murouse_membrane_v1_membrane_proto_init() {
	if File_murouse_membrane_v1_membrane_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_murouse_membrane_v1_membrane_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_murouse_membrane_v1_membrane_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_murouse_membrane_v1_membrane_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_murouse_membrane_v1_membrane_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_murouse_membrane_v1_membrane_proto_goTypes,
		DependencyIndexes: file_murouse_membrane_v1_membrane_proto_depIdxs,
		EnumInfos:         file_murouse_membrane_v1_membrane_proto_enumTypes,
		MessageInfos:      file_murouse_membrane_v1_membrane_proto_msgTypes,
		ExtensionInfos:    file_murouse_membrane_v1_membrane_proto_extTypes,
	}.Build()
	File_murouse_membrane_v1_membrane_proto = out.File
	file_murouse_membrane_v1_membrane_proto_rawDesc = nil
	file_murouse_membrane_v1_membrane_proto_goTypes = nil
	file_murouse_membrane_v1_membrane_proto_depIdxs = nil
}
